#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

# Generate SSH host keys and persist them in /data/system/ssh
mkdir -p /data/system/ssh
mount --bind /data/system/ssh /etc/ssh
ssh-keygen -A
umount /etc/ssh

mkdir -p /data/system/log

mount -t tmpfs tmpfs -o size=16m /mnt/overlays

mkdir -p /mnt/overlays/etc/work /mnt/overlays/etc/upper
mount -t overlay overlay -o lowerdir=/etc,upperdir=/mnt/overlays/etc/upper,workdir=/mnt/overlays/etc/work /etc

mkdir -p /mnt/overlays/var/work /mnt/overlays/var/upper
mount -t overlay overlay -o lowerdir=/var,upperdir=/mnt/overlays/var/upper,workdir=/mnt/overlays/var/work /var

umount /proc
umount /sys
umount /dev

mount -t tmpfs tmpfs /tmp
mount -t tmpfs tmpfs /home/cage/.cache
mount -t tmpfs tmpfs /home/cage/.config

#sh

exec /sbin/init
